auth:
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

# catalog:
#   rules:
#     - allow: [Component, System, Group, Resource, Location, Template, API, User, Domain]
#   locations:
#     # - type: file
#     #   target: /opt/app-root/src/configs/catalog-entities/users.yaml
#     #   rules:
#     #     - allow: [User, Group]
#     # - type: file
#     #   target: /opt/app-root/src/configs/catalog-entities/components.yaml
#     #   rules:
#     #     - allow: [Component, System]
#     # - type: url
#     #   target: https://github.com/devurandomsorg/backstage-catalog/blob/main/all.yaml
#     # - type: url
#     #   target: https://github.com/devurandomsorg/backstage-catalog/blob/main/acme-corp.yaml
#     # - type: url
#     #   target: https://github.com/devurandomsorg/backstage-catalog/blob/main/acme-corp.yaml
#     - type: url
#       target: https://github.com/redhat-developer/red-hat-developer-hub-software-templates/blob/main/templates.yaml
#     - type: url
#       target: https://github.com/b4mad/racing-manifests/blob/main/catalog-info.yaml
#       # rules:
#       #   - allow: [Component, User, Group, Domain]
#   providers:
#     github:
#       providerId:
#         organization: 'b4mad'
#         schedule:
#           initialDelay: { seconds: 30 }
#           frequency: { hours: 1 }
#           timeout: { minutes: 50 }
#     githubOrg:
#       id: development
#       githubUrl: https://github.com
#       orgs: ['b4mad']
#       schedule:
#         initialDelay: { seconds: 30 }
#         frequency: { hours: 1 }
#         timeout: { minutes: 50 }

# permission:
#   enabled: true
#   rbac:
#     policies-csv-file: ./rbac-policy.csv
#     policyFileReload: true
#     admin:
#       users:
#         - name: user:default/durandom
#         - name: user:default/goern