apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: default
  description: Default Group
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user
spec:
  memberOf: [group:default]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: admin
spec:
  memberOf: [group:default]
