apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhdh-simple
configMapGenerator:
- name: app-config-rhdh
  files:
  - app-config.local.yaml
# - name: dynamic-plugins
#   files:
#   - dynamic-plugins.yaml
# - name: rbac-policy
#   files:
#   - rbac-policy.csv
# secretGenerator:
# - name: secret-rhdh
#   envs:
#   - secret.env
# - name: github-app-credentials
#   files:
#   - github-app-credentials.yaml
resources:
- namespace.yaml
- backstage.yaml
configurations:
- kustomizeconfig/backstage.yaml
