apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhdh-simple
configMapGenerator:
- name: app-config-rhdh
  files:
  - app-config.local.yaml
- name: dynamic-plugins
  files:
  - dynamic-plugins.yaml
- name: catalog
  files:
  - catalog.yaml
- name: rbac-policy
  files:
  - rbac-policy.csv
- name: conditional-policies
  files:
  - conditional-policies.yaml

secretGenerator:
- name: secret-rhdh
  envs:
  - secret.env
resources:
- namespace.yaml
- backstage.yaml
- keycloak.yaml
- pvc-dynamic-plugins-root.yaml
configurations:
- kustomizeconfig/backstage.yaml
