apiVersion: rhdh.redhat.com/v1alpha2
kind: Backstage
metadata:
  name: rhdh
spec:
  application:
    route:
      # we use ingress.yaml
      enabled: false
      # host: backstage-rhdh-rhdh-test
      # subdomain: apps.phobos.b4mad.emea.operate-first.cloud
      # tls:
      #   certificate: "certificatecontent"
      #   externalCertificateSecretName: "my-certificate"
      #   key: "keycontent"
      #   caCertificate: "caCertificatecontent"
    # image: quay.io/rhdh/rhdh-hub-rhel9:1.3
    # https://catalog.redhat.com/software/containers/rhdh/rhdh-hub-rhel9/645bd4c15c00598369c31aba?container-tabs=gti
    image: registry.redhat.io/rhdh/rhdh-hub-rhel9@sha256:9bf7c29fd61551036508686410de950ff1f46568c396429281a3d506922a7a81
    dynamicPluginsConfigMapName: dynamic-plugins
    appConfig:
      configMaps:
        - name: app-config-rhdh
    extraEnvs:
      secrets:
        - name: secret-rhdh
    extraFiles:
      configMaps:
        - name: rbac-policy
      secrets:
        - name: github-app-credentials
          key: github-app-credentials.yaml
  deployment:
    patch:
      spec:
        template:
          spec:
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root