apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-read-only
rules:
- apiGroups:
  - "*"
  resources:
    - pods
    - pods/log
    - configmaps
    - services
    - deployments
    - replicasets
    - horizontalpodautoscalers
    - ingresses
    - statefulsets
    - limitranges
    - resourcequotas
    - daemonsets
    - jobs
    - cronjobs
  verbs:
    - get
    - watch
    - list
- apiGroups:
    - route.openshift.io
  resources:
    - routes
  verbs:
    - get
    - list
- apiGroups:
    - tekton.dev
  resources:
    - pipelines
    - pipelineruns
    - taskruns
  verbs:
    - get
    - list

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
  name: backstage-read-only

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-read-only
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backstage-read-only
subjects:
  - kind: ServiceAccount
    name: backstage-read-only

---

apiVersion: v1
kind: Secret
metadata:
  name: backstage-read-only
  annotations:
    kubernetes.io/service-account.name: backstage-read-only
type: kubernetes.io/service-account-token

